name: jasara_poc
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  http: ^1.4.0
  provider: ^6.1.5
  dotted_border: ^2.1.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/logos/jasara_small_icon.svg
    - assets/logos/logo.svg
    - assets/fonts/Urbanist/
    - assets/fonts/
    - assets/images/
    - assets/images/flags/
    - assets/images/flags/arabic_language_flag.png
    - assets/images/flags/english_language.jpeg
    - assets/images/download.jpeg
    - assets/fonts/Urbanist/static/
    
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/static/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/static/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/static/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/static/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist/static/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Urbanist/static/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic
