// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTTxyDiJ4Ywmz6rQbBn6WLEX0m-XC7qo',
    appId: '1:375800134189:web:e680efb714a9f88eb716a4',
    messagingSenderId: '375800134189',
    projectId: 'jasara-poc',
    authDomain: 'jasara-poc.firebaseapp.com',
    storageBucket: 'jasara-poc.firebasestorage.app',
    measurementId: 'G-PLVW7T1KE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhacAiKqV0QiYeeQNYhCCzglof_xfIa7Y',
    appId: '1:375800134189:android:1d023c40fbc45076b716a4',
    messagingSenderId: '375800134189',
    projectId: 'jasara-poc',
    storageBucket: 'jasara-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8A4kJdMjJgb2dzzx3AO5YEiw_CQwR-8',
    appId: '1:375800134189:ios:caba4f7c9b1fe2e3b716a4',
    messagingSenderId: '375800134189',
    projectId: 'jasara-poc',
    storageBucket: 'jasara-poc.firebasestorage.app',
    iosBundleId: 'com.example.jasaraPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8A4kJdMjJgb2dzzx3AO5YEiw_CQwR-8',
    appId: '1:375800134189:ios:caba4f7c9b1fe2e3b716a4',
    messagingSenderId: '375800134189',
    projectId: 'jasara-poc',
    storageBucket: 'jasara-poc.firebasestorage.app',
    iosBundleId: 'com.example.jasaraPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbTTxyDiJ4Ywmz6rQbBn6WLEX0m-XC7qo',
    appId: '1:375800134189:web:555c138f7439d446b716a4',
    messagingSenderId: '375800134189',
    projectId: 'jasara-poc',
    authDomain: 'jasara-poc.firebaseapp.com',
    storageBucket: 'jasara-poc.firebasestorage.app',
    measurementId: 'G-YXXRYKLB5X',
  );
}
